- name: Agregar repo Kubernetes
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  args:
    creates: /etc/apt/sources.list.d/kubernetes.list

- name: Instalar kubeadm, kubelet y kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Mantener versiones fijas
  command: apt-mark hold kubelet kubeadm kubectl

- name: Inicializar cluster en master
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  when: inventory_hostname == "k8s-master"
  args:
    creates: /etc/kubernetes/admin.conf

- name: Configurar kubeconfig en master
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/{{ ansible_user }}/.kube
    - cp -i /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
    - chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config
  when: inventory_hostname == "k8s-master"

- name: Instalar red Flannel en master
  become: false
  command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  when: inventory_hostname == "k8s-master"
